### ISSUE TITLE
A big thanks! 

### ISSUE THREAD

**Issue by ab15Kath** [cytan299/ap_hand_controller#3]
![IMG_20210321_172254639_HDR](https://user-images.githubusercontent.com/63481575/112726965-77ec3580-8ef6-11eb-985f-35c8aed5c815.jpg)

![2021 M42 M43 1-120flat100lum ncina levels intersection 2](https://user-images.githubusercontent.com/63481575/112727735-4b3a1d00-8efa-11eb-94ae-57c56f8ae736.JPG)
I've attached a photo of the finished hand controller. I went with a white case to match equipment and I prefer white at night with my glasses. If I may suggest, after looking at previous versions of your PCB, that it appears the source of the previous power issue was the connection between C7 and the East side of the thumb joystick. I think once the MOSFET was removed the power strip needed to stay in place to complete the circuit. I used the hand controller recently to image M42 & M43 and it was a joy to use. Once again, I thank you for your excellent AP Hand Controller design. Andrew    As a final note I've included the M42 & M43 image - so much easier to frame using your hand controller.

**Comment by cytan299** [comment]
Hi Andrew,
   A big thanks for finding the wiring bug! I've corrected the PCB and will upload it later.  I believe you're the first person to build my hand controller and that's why the bug was not discovered until now.  
   As for the hand controller, I use mine all the time, during every imaging session to Polar Align. I hope it'll work for you as well as for me.

cytan
